# A sample Makefile for building Google Test and using it in user
# tests.  Please tweak it to suit your environment and project.  You
# may want to move it to your project's root directory.
#
# SYNOPSIS:
#
#   make [all]  - makes everything.
#   make TARGET - makes the given target.
#   make clean  - removes all files generated by make.

# Please tweak the following variable definitions as needed by your
# project, except GTEST_HEADERS, which you can use in your own targets
# but shouldn't modify.

# Flags passed to the preprocessor.
# Set Google Test's header directory as a system directory, such that
# the compiler doesn't generate warnings in Google Test headers.
CPPFLAGS += -I./testcase/include -I./leetcode/include -I./gtest/include

# Flags passed to the C++ compiler.
CXXFLAGS += -g -Wall -Wextra -pthread -L./gtest/lib/ -lgtest

# All tests produced by this Makefile.  Remember to add new tests you
# created to the list.
TESTS = main

TOP_PATH = $(shell pwd)
SRC_PATH = $(TOP_PATH)/leetcode/src
DIRS = $(shell find $(SRC_PATH) -maxdepth 3 -type d)

SRCS_CPP += $(foreach dir, $(DIRS), $(wildcard $(dir)/*.cpp))
SRCS_CPP += ./testcase/src/leetcode_test.cpp
OBJS_CPP = $(patsubst %.cpp, %.o, $(SRCS_CPP))

#https://www.cnblogs.com/catgatp/p/6527251.html

# All Google Test headers.  Usually you shouldn't change this
# definition.
GTEST_HEADERS = include/gtest/*.h \
                include/gtest/internal/*.h

# House-keeping build targets.

all : $(TESTS)

clean :
	rm -f $(TESTS) $(OBJS_CPP)

# Builds a sample test.  A test should link with either gtest.a or
# gtest_main.a, depending on whether it defines its own main()
# function.

main : $(OBJS_CPP)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -lpthread $^ -o $@
