# A sample Makefile for building Google Test and using it in user
# tests.  Please tweak it to suit your environment and project.  You
# may want to move it to your project's root directory.
#
# SYNOPSIS:
#
#   make [all]  - makes everything.
#   make TARGET - makes the given target.
#   make clean  - removes all files generated by make.

# Please tweak the following variable definitions as needed by your
# project, except GTEST_HEADERS, which you can use in your own targets
# but shouldn't modify.

# Flags passed to the preprocessor.
# Set Google Test's header directory as a system directory, such that
# the compiler doesn't generate warnings in Google Test headers.
CPPFLAGS += -I./testcase/include -I./leetcode/include -I./gtest/include

# Flags passed to the C++ compiler.
CXXFLAGS += -g -Wall -Wextra -pthread -L./gtest/lib/ -lgtest

# All tests produced by this Makefile.  Remember to add new tests you
# created to the list.
TESTS = main

# All Google Test headers.  Usually you shouldn't change this
# definition.
GTEST_HEADERS = include/gtest/*.h \
                include/gtest/internal/*.h

# House-keeping build targets.

all : $(TESTS)

clean :
	rm -f $(TESTS) *.o



# Builds a sample test.  A test should link with either gtest.a or
# gtest_main.a, depending on whether it defines its own main()
# function.

CandyL135.o : ./leetcode/src/CandyL135.cpp
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c ./leetcode/src/CandyL135.cpp

AssignCookiesL455.o : ./leetcode/src/AssignCookiesL455.cpp
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c ./leetcode/src/AssignCookiesL455.cpp

leetcode_test.o : ./testcase/src/leetcode_test.cpp
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c ./testcase/src/leetcode_test.cpp

main : leetcode_test.o AssignCookiesL455.o CandyL135.o
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -lpthread $^ -o $@
